[project]
name = "isef01-lernzeit-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "reginaleis", email = "128072671+reginaleis@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "mypy>=2.3.1",
    "ruff>=0.16.9",
    "uvicorn>=0.53.0",
]

[project.scripts]
isef01-lernzeit-manager = "isef01_lernzeit_manager:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"] # Pyflakes, Error, Isort, Upgrade, Bugbear
ignore = []

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
