[project]
name = "isef01-lernzeit-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "reginaleis", email = "128072671+reginaleis@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
isef01-lernzeit-manager = "isef01_lernzeit_manager:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
